### ISSUE TITLE
Traceback (most recent call last):   File "/Users/liuyuhang/Desktop/Python/untitled3/test/testThress.py", line 39, in <module>     writeGif(filename, images, duration=0.5, subRectangles=False)   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/images2gif/images2gif.py", line 593, in writeGif     gifWriter.writeGifToFile(fp, images, duration, loops, xy, dispose)   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/images2gif/images2gif.py", line 449, in writeGifToFile     fp.write(globalPalette) TypeError: argument 1 must be string or buffer, not None

### ISSUE THREAD

**Issue by 2240054474** [OmarIbannez/image2gif_example#1]
Traceback (most recent call last):
  File "/Users/liuyuhang/Desktop/Python/untitled3/test/testThress.py", line 39, in <module>
    writeGif(filename, images, duration=0.5, subRectangles=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/images2gif/images2gif.py", line 593, in writeGif
    gifWriter.writeGifToFile(fp, images, duration, loops, xy, dispose)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/images2gif/images2gif.py", line 449, in writeGifToFile
    fp.write(globalPalette)
TypeError: argument 1 must be string or buffer, not None

为何我报错呢

**Comment by MarcRamos** [comment]
I am getting the same error now with, with python2 and version images2gif==1.0.1 Can somebody provide an answer?
I am writing the gif like:
writeGif(local_gif, images, duration=2, subRectangles=False, dither=0)

Thanks!
